# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: festango.net
email: shun@festango.net
description: > 
  My personal weblog content convering my projects, thought, and more.
baseurl: "/"
url: "https://festango.net/
twitter_username: festango
github_username:  festango

# Build settings
markdown: kramdown
